### ISSUE TITLE
rbac基础表的dao类

### ISSUE THREAD

**Issue by yankj12** [yankj2/rbac#2]

**Comment by yankj12** [comment]
严格来说功能权限也应该属于rbac权限系统的基础表，不过目前先实现数据权限功能，再实现菜单功能，最终实现完全的功能权限

**Comment by veotax** [comment]
please try jCasbin here: https://github.com/casbin/jcasbin

**Comment by yankj12** [comment]
@veotax Thank you very much. I will consider using it in the future.
